<a href="https://colab.research.google.com/github/AIDE-00001/Portafolio/blob/main/Estilizacion_de_tablas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Visualization: Estilizando tablas con python**

## **Extracción y preparación de los datos**

In [1]:
# !pip install pandas==2.0.0

In [2]:
import pandas as pd
#para ver la version que tenemos
print(pd.__version__)

2.2.2

In [3]:
#creamos el data frame ventas y lo leemos con pandas
ventas = pd.read_csv('https://gist.githubusercontent.com/ahcamachod/d2efadda3f3833d65da750c64705ac42/raw/80aef6f3bad210d34b67ed85565f039a30e2d9e0/ventas.csv', sep='#')
#vamos a ver las primeras filas
ventas.head()

,fecha_pedido,fecha_envio,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,precio_base,precio_unit_sin_descuento,descuento,precio_unit_venta,cantidad,ventas,ganancia
0,2018-11-09,2018-11-12,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,409.70,445.33,0.000,445.33,2,890.66,71.26
1,2018-11-09,2018-11-12,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,705.10,829.53,0.000,829.53,3,2488.59,373.29
2,2018-06-13,2018-06-17,Económica,Matías González,B2B,Córdoba,Córdoba,Central,Jardinería y paisajismo,Semillas,19.02,24.86,0.000,24.86,2,49.72,11.68
3,2017-10-12,2017-10-19,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Materiales de construcción,Materiales de revestimiento,781.38,840.19,0.225,651.15,5,3255.75,-651.15
4,2017-10-12,2017-10-19,Entrega estándar,Lucas González,B2C,Gualeguay,Entre Ríos,Litoral,Jardinería y paisajismo,Macetas,35.88,42.24,0.100,38.02,2,76.04,4.28

In [4]:
#vamos a recrear [[columnas que queremos]]
ventas = ventas[['fecha_pedido','modo_envio','nombre_cliente','segmento_cliente','ciudad','provincia','region','departamento','tipo_producto','ventas','cantidad','ganancia']]
#Solo queremos ver las primeras 2 filas
ventas.head(2)

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia
0,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,890.66,2,71.26
1,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,2488.59,3,373.29

In [5]:
#Ver el tamaño de data frame(8940 filas, 12columnas)
ventas.shape

(8940, 12)

In [6]:
#para ver como estan las filas la integridad de nuestros datos
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha_pedido      8940 non-null   object
 1   modo_envio        8940 non-null   object
 2   nombre_cliente    8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   ciudad            8940 non-null   object
 5   provincia         8940 non-null   object
 6   region            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_producto     8940 non-null   object
 9   ventas            8940 non-null   float64
 10  cantidad          8940 non-null   int64
 11  ganancia          8940 non-null   float64
dtypes: float64(2), int64(1), object(9)
memory usage: 838.3+ KB

In [7]:
#Fecha pedido convertilo en datetime con ayuda pd.to_datime(columna, formato de la fecha)
ventas['fecha_pedido'] = pd.to_datetime(ventas['fecha_pedido'],format='%Y-%m-%d')
#ver las primeras 2 filas
ventas.head(2)

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia
0,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,890.66,2,71.26
1,2018-11-09,Económica,Gaspar Fernández,B2C,Lomas de Zamora,Buenos Aires,Buenos Aires,Materiales de construcción,Herramientas,2488.59,3,373.29

In [8]:
#vemos si se cambio (se ve que ya convertimos a date time)
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8940 entries, 0 to 8939
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fecha_pedido      8940 non-null   datetime64[ns]
 1   modo_envio        8940 non-null   object
 2   nombre_cliente    8940 non-null   object
 3   segmento_cliente  8940 non-null   object
 4   ciudad            8940 non-null   object
 5   provincia         8940 non-null   object
 6   region            8940 non-null   object
 7   departamento      8940 non-null   object
 8   tipo_producto     8940 non-null   object
 9   ventas            8940 non-null   float64
 10  cantidad          8940 non-null   int64
 11  ganancia          8940 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 838.3+ KB

## Misión 1: Equipo de Ventas

Necesitamos construir una visualización para indicar los **10 principales clientes por total de ventas**.

Con ello, el equipo de ventas puede pensar en estrategias para mantener a estos clientes comprando en nuestra tienda.

In [9]:
#crear un nuevo data frame donde queremos agrupa(por el nombre de cliente unicamente la columna de
# ventas)sumar las ventas.quiero los 10 mas relevante.generar una copia
clientes = ventas.groupby(['nombre_cliente'])['ventas'].sum().nlargest(10).copy()
#para que no quede como una serie resetear el indice
clientes = clientes.reset_index()
#vizualisamos
clientes

      nombre_cliente    ventas
0    Víctor Carrasco  73370.61
1        Brisa Rojas  68868.11
2       Mateo Vargas  62749.75
3      Vicente Rojas  59544.11
4        Laura Rojas  51398.87
5         Lucía Díaz  48178.99
6   Cristina Barrios  47610.80
7  Alejandro Sánchez  43769.25
8      Pamela Huerta  42354.19
9     Carlos Sánchez  41238.81

In [10]:
# dic = {'nombre_cliente':'Clientes', 'ventas':'Ventas'}-->*
# clientes = clientes.rename(columns=dic)-->
# * es otra foma de hacerlo

#asignamos la lista (colmna cliente,columna ventas)-->ambas deben tenner las mismas filas de lo contrario debemos crear un diccioonario primero
clientes.columns = ['Clientes','Ventas']
#para el ranki podemostomar los clientes y sumar 1
clientes['Ranking'] = clientes.index + 1
#dejar que el ranking sea como el indice parametro inplace=true
clientes.set_index('Ranking', inplace = True)
#visualizamos
clientes

                  Clientes    Ventas
Ranking
1          Víctor Carrasco  73370.61
2              Brisa Rojas  68868.11
3             Mateo Vargas  62749.75
4            Vicente Rojas  59544.11
5              Laura Rojas  51398.87
6               Lucía Díaz  48178.99
7         Cristina Barrios  47610.80
8        Alejandro Sánchez  43769.25
9            Pamela Huerta  42354.19
10          Carlos Sánchez  41238.81

In [11]:
#style es un obejeto que puede cambiar el formato:letra,fuente,color,si es cursiva...
estilo = clientes.style
estilo

In [12]:
#cambiamos el fomato(llave ventas:el formato que quiero)
estilo.format({'Ventas':'{:,.2f}'})
estilo

# Misión 2: Equipo Comercial

Necesitamos construir una visualización que permita asociar el **total de ventas y el total de lucros por tipo de producto**.

Ello permitirá que el equipo comercial pueda enfocarse en estrategias para apalancar los ingresos que se reciben con cada tipo de producto vendido en la tienda.

In [13]:
#crear un nuevo data frame agrupoamos(tipo de producto)tomamos la culumna ventas,ganancias. suma
#cuando hay doble corchete creamos el data frame
ganancias_ventas = ventas.groupby(['tipo_producto'])[['ventas','ganancia']].sum()
ganancias_ventas

                                 ventas  ganancia
tipo_producto
Brotes                          8811.32   1381.42
Decoración de jardín           82680.08   9939.43
Equipos de limpieza           542304.58   8724.39
Fertilizantes                  53144.74  11254.88
Fontanería                    373223.88  -5622.34
Herramientas                  995158.41  41020.34
Herramientas automotrices     502109.29  63330.22
Herramientas de jardinería    648879.72  53202.88
Iluminación                   275229.53  20264.54
Macetas                       696044.18  33941.85
Materiales de paisajismo      150552.49  -1912.37
Materiales de revestimiento   629656.36 -28869.01
Muebles de exterior           328932.27  26784.59
Neumáticos                   1022428.97  67460.05
Pesticidas                    244956.04  53343.89
Piezas de repuesto            486907.94  91148.67
Semillas                       39979.75   8865.09

In [14]:
#asignamos al nombre del indice =tipo de producto
ganancias_ventas.index.name = 'tipo de producto'
ganancias_ventas

                                 ventas  ganancia
tipo de producto
Brotes                          8811.32   1381.42
Decoración de jardín           82680.08   9939.43
Equipos de limpieza           542304.58   8724.39
Fertilizantes                  53144.74  11254.88
Fontanería                    373223.88  -5622.34
Herramientas                  995158.41  41020.34
Herramientas automotrices     502109.29  63330.22
Herramientas de jardinería    648879.72  53202.88
Iluminación                   275229.53  20264.54
Macetas                       696044.18  33941.85
Materiales de paisajismo      150552.49  -1912.37
Materiales de revestimiento   629656.36 -28869.01
Muebles de exterior           328932.27  26784.59
Neumáticos                   1022428.97  67460.05
Pesticidas                    244956.04  53343.89
Piezas de repuesto            486907.94  91148.67
Semillas                       39979.75   8865.09

In [15]:
#crear nuestro estilo_producto= aplicar la propiedad style a gnacias ventas
estilo_producto = ganancias_ventas.style
estilo_producto

In [42]:
#Vamos a darle un formato(primero dejarlo en 2 cifras decimales,separar ,para separaralo miles)que muestre USD
estilo_producto.format('USD {:,.2f}')

In [44]:
#Vamos a utilizar para resartal el valor maximo y el valor minimo
#.higlight_max es resaltar(color).higlith_min resaltar(red)
#lo almacenamos
estilo_producto = estilo_producto.format('USD {:,.2f}').highlight_max(color='lightgreen').highlight_min(color='red')
estilo_producto

In [45]:
#tecnica para meojorar la presentacion usando un a escala de colores
#para se intesigique cuando se mas  se vende y menos color con lo que menos se venda
#esto lo podemos acer con el metodo bakgroup(colocar el mapa de colores en este caso verde)
estilo_producto.background_gradient(cmap='Greens')

In [46]:
#trabajaremos con css se parece a los diccinarios de python
#objeto llamado encabezado{debmos estrablecer lo paramtros selector (a que le vamos hacer la modificaion) y propiedades que vamos alterar en el  }
#props:colocar las propiedades respetando cada un de las categorias que tiene
encabezado = {
              'selector':'th',
              'props':'font-weight:bold; font-family:Arial; text-align:center; text-transform:capitalize'
}

In [47]:
#vamos aplicarlo a nuesto estilo(estilo,overwrite=false es para que no se pierda las tranformaciones que hemos realizado)
estilo_producto.set_table_styles([encabezado],overwrite=False)

# Misión 3: Equipo de Logística

Necesitamos construir una visualización que nos permita entender la **distribución de pedidos por región en Argentina**.

Así, el equipo de logística va a saber dónde hay más oportunidad de enfocar los esfuerzos de material y mano de obra.

In [48]:
#preparando nuestrosdatos
#creamos un data frame(vamos hacer un conteo de ventas por regiones)
region = pd.DataFrame(ventas['region'].value_counts())
#vamos a modificar el nombre de la columna y le asignamos el nomre
region.columns = ['N° Pedidos']
#vamos a cambiar el nombre del indice
region.index.name = 'Región'
#guardamos en una variable
region

              N° Pedidos
Región
Buenos Aires        2822
Litoral             1924
Norte               1555
Central             1276
Cuyo                 915
Patagónica           448

In [49]:
#importamos la libreria numpy nos ayuda de forma mas eficiente con numeros
import numpy as np

In [50]:
#Crear variable (almcenamos los porcentajes)convertila en un to_numpy
porcentaje = region['N° Pedidos'].to_numpy()
#multiplicamos por 100 dividido entre la suma
porcentaje = 100*porcentaje/porcentaje.sum()
#visualizar el porcntaje
porcentaje

array([31.56599553, 21.5212528 , 17.39373602, 14.27293065, 10.23489933,
        5.01118568])

In [52]:
#crear nueva columna la almacenamos en porcentaje
region['Porcentaje de Pedidos'] = porcentaje
#visualizamos
region

              N° Pedidos  Porcentaje de Pedidos
Región
Buenos Aires        2822              31.565996
Litoral             1924              21.521253
Norte               1555              17.393736
Central             1276              14.272931
Cuyo                 915              10.234899
Patagónica           448               5.011186

In [53]:
#creacion de nuestro estilo
estilo_region = region.style
#visualizamos
estilo_region

In [63]:
#vamos a aliniear los encabezados y que nuestra tabla sea todo en blaco utilizando css
encabezado = {
              'selector':'th',
              'props':'font-weight:bold; font-family:Arial; text-align:right; background-color:white'
}
#props:peso de la fuente:bold,familia de fuente arial,aliniacion a la derecha,color de bacgrund=blanco
#para los datos(celdas)
#en selector en lugae de th va ser td=table data
celdas = {
              'selector':'td',
              'props':'background-color:white'
}

estilo_region.set_table_styles([encabezado,celdas])

In [27]:
#vamos a darle formato unicamente columna porcentaje pedidos
estilo_region.format({'Porcentaje de Pedidos':'{:.2f} %'})\
                    .bar(subset='Porcentaje de Pedidos',vmin=0,vmax=100,color='#9cd3bb')

# Misión 4: Equipo de Logística

Nuevamente el equipo de logística desea replantear su estructura y organización de provisionamiento de productos e, para ello, se pensó en una visualización que permita identificar el estándar de la **cantidad de productos solicitados por mes por departamento**.

In [64]:
#creamos un nuevo data frame que es copia de ventas
meses = ventas.copy()
#organizar el data frame por la fecha de pedido
meses = meses.sort_values('fecha_pedido')
#visualizamos
meses

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia
7171,2016-01-04,Entrega estándar,Ramiro Guzmán,B2C,Rosario,Santa Fe,Litoral,Jardinería y paisajismo,Pesticidas,55.92,2,9.44
651,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,12.04,2,-9.32
650,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Macetas,927.30,3,-110.13
649,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Semillas,40.08,3,7.26
1576,2016-01-06,Entrega estándar,Florencia Chávez,B2C,Ciudad Autónoma de Buenos Aires,Ciudad Autónoma de Buenos Aires,Buenos Aires,Jardinería y paisajismo,Decoración de jardín,66.42,3,8.31
...,...,...,...,...,...,...,...,...,...,...,...,...
796,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,179.43,3,33.63
795,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Automotriz,Neumáticos,309.19,7,4.69
794,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,1098.68,4,20.60
1151,2019-12-31,Entrega estándar,Francisco Cárdenas,B2B,Quilmes,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,47.28,2,7.68
1152,2019-12-31,Entrega estándar,Francisco Cárdenas,B2B,Quilmes,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,70.44,2,11.00

In [65]:
#tomar el data frame creamos el atribo mes vamo atomar de meses la columna fecha pdido.strtime(formato de string para tiempo)
meses['mes'] = meses['fecha_pedido'].dt.strftime('%Y - %b')
#vamos a quitar el idice
meses = meses.reset_index(drop=True)
#visulizamos
meses

,fecha_pedido,modo_envio,nombre_cliente,segmento_cliente,ciudad,provincia,region,departamento,tipo_producto,ventas,cantidad,ganancia,mes
0,2016-01-04,Entrega estándar,Ramiro Guzmán,B2C,Rosario,Santa Fe,Litoral,Jardinería y paisajismo,Pesticidas,55.92,2,9.44,2016 - Jan
1,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,12.04,2,-9.32,2016 - Jan
2,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Macetas,927.30,3,-110.13,2016 - Jan
3,2016-01-05,Entrega estándar,Jerónimo Cortés,B2B,Pergamino,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Semillas,40.08,3,7.26,2016 - Jan
4,2016-01-06,Entrega estándar,Florencia Chávez,B2C,Ciudad Autónoma de Buenos Aires,Ciudad Autónoma de Buenos Aires,Buenos Aires,Jardinería y paisajismo,Decoración de jardín,66.42,3,8.31,2016 - Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8935,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,179.43,3,33.63,2019 - Dec
8936,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Automotriz,Neumáticos,309.19,7,4.69,2019 - Dec
8937,2019-12-31,Entrega estándar,Olivia Aguilar,B2C,La Plata,Buenos Aires,Buenos Aires,Materiales de construcción,Fontanería,1098.68,4,20.60,2019 - Dec
8938,2019-12-31,Entrega estándar,Francisco Cárdenas,B2B,Quilmes,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,47.28,2,7.68,2019 - Dec
8939,2019-12-31,Entrega estándar,Francisco Cárdenas,B2B,Quilmes,Buenos Aires,Buenos Aires,Jardinería y paisajismo,Herramientas de jardinería,70.44,2,11.00,2019 - Dec

In [67]:
#crear una tabla dinamica es ecificando (que podamos ver todas las columnas)
pd.set_option('display.max_columns',None)

In [68]:
#pivot table es una tabla dinamica(idice van hacer los departamentos, columnas van se la columna mes, los valores va a ser la columna cantidad, columna de agregacion va ser lla suma,paraque lo deje tal cual con sort=false)
ventas_mensuales = meses.pivot_table(index=meses.departamento, columns='mes', values='cantidad', aggfunc='sum', sort=False)
#visualizamos
ventas_mensuales

mes,2016 - Jan,2016 - Feb,2016 - Mar,2016 - Apr,2016 - May,2016 - Jun,2016 - Jul,2016 - Aug,2016 - Sep,2016 - Oct,2016 - Nov,2016 - Dec,2017 - Jan,2017 - Feb,2017 - Mar,2017 - Apr,2017 - May,2017 - Jun,2017 - Jul,2017 - Aug,2017 - Sep,2017 - Oct,2017 - Nov,2017 - Dec,2018 - Jan,2018 - Feb,2018 - Mar,2018 - Apr,2018 - May,2018 - Jun,2018 - Jul,2018 - Aug,2018 - Sep,2018 - Oct,2018 - Nov,2018 - Dec,2019 - Jan,2019 - Feb,2019 - Mar,2019 - Apr,2019 - May,2019 - Jun,2019 - Jul,2019 - Aug,2019 - Sep,2019 - Oct,2019 - Nov,2019 - Dec
departamento,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Jardinería y paisajismo,161,87,277,323,270,273,348,339,549,276,716,525,97,131,278,271,269,321,268,322,663,260,746,628,190,177,260,338,463,473,413,380,757,402,727,770,361,205,458,415,542,490,423,561,929,617,946,989
Automotriz,45,20,46,107,81,83,91,95,154,85,236,154,55,44,74,111,94,59,88,117,180,100,179,235,59,49,112,72,124,118,117,123,181,103,253,189,109,63,167,87,150,170,168,136,280,205,331,252
Materiales de construcción,60,23,102,69,91,114,104,101,182,94,213,269,93,38,100,85,76,120,128,106,194,129,259,258,91,67,127,128,171,117,132,113,227,171,308,294,83,67,107,131,172,151,162,132,282,213,312,395

In [69]:
#Fijar los nombres de lo que representa cada uno de los indices
#creams nuestro estilo tomamos nuestro data frame ventas _mesuales
estilo_mensual = ventas_mensuales.style
#visualizamos
estilo_mensual

In [70]:
#vamos a dejarlo fijo(que queremos dejar fijo axis=index)
estilo_mensual.set_sticky(axis='index')

In [71]:
#mejorar el formato de la tabla
#Creamos nuestros dicionarios
#{solo quermos la columna, propiedades }
columnas = {
            'selector':'.col_heading',
            'props':'font-weight:normal; font-family:Arial'
}
#establecer para la tabla{tabla,datos, propiedades la alineacion}
tabla = {
            'selector':'td,th',
            'props':'text-align:left'
}
#vamos a tabjar en los indices{index_name,propiedades alinear a la derecha..}
indices = {
            'selector':'.index_name',
            'props':'font-weight:bold; font-family:Arial; text-align:right'
}
#tomar nestros estilo mensual([]overwrite=false para no perder lo que hemos realizado)
estilo_mensual.set_table_styles([columnas,tabla,indices], overwrite=False)

# Misión 5: Informe de Desempeño

El informe de desempeño es un documento muy importante para la empresa. En este, todos los que trabajan en la tienda pueden entender cómo está la empresa. Debido a ello, las tablas bien construídas son esenciales para mostrar los datos de la mejor forma.

Por lo tanto, necesitamos construir una visualización que permita entender la **relación entre tipos de clientes y modo de envío de productos de acuerdo con las ventas**. De esta forma, será posible destacar en el informe cuál es el modo de envío y cuáles son los que más generaron lucro en las ventas.

In [73]:
#Vamos a tomar nuevo data frame(vamo a tener clientes, tipo de eenvio,los valores van a ser las ventas, la funcion de agregacion va se la suma)
df_cliente = ventas.pivot_table(index='segmento_cliente',columns='modo_envio',values='ventas',aggfunc='sum')
#visualizamos
df_cliente

modo_envio,Económica,Entrega en 24 horas,Entrega estándar,Envío rápido
segmento_cliente,,,,
B2B,718461.22,217465.60,1884738.56,602049.40
B2C,729174.73,182531.47,2248283.69,498294.88

In [74]:
#Necesitamos los valores totale(creamos dos nuevos atributos)
# es igul a la suma de las columnas
df_cliente['Total'] = df_cliente.sum(axis=1)
#crear la columna en el indice, hacemos la suma
df_cliente.loc['Total'] = df_cliente.sum()
#visualizamos
df_cliente

modo_envio,Económica,Entrega en 24 horas,Entrega estándar,Envío rápido,Total
segmento_cliente,,,,,
B2B,718461.22,217465.60,1884738.56,602049.40,3422714.78
B2C,729174.73,182531.47,2248283.69,498294.88,3658284.77
Total,1447635.95,399997.07,4133022.25,1100344.28,7080999.55

In [75]:
#creamos un estilo, formato a toda la tabla
compra_cliente = df_cliente.style.format('{:,.2f}')
#visualizamos
compra_cliente

In [76]:
#crar nuestro diccionario tabla y le colocamos los parameros que deseamos, not(.index_name)es para que no se lo agrege a los indice
tabla={
    'selector':'td,th:not(.index_name)',
    'props':'font-weight:normal; font-family:Arial; text-align:center: background-color:white'
}
#crear diccionario para los indices
indice={
    'selector':'.index_name',
    'props':'font-weight:normal; font-style:italic; text-align:right: color:#696969'
}
#tomamos nuestro estilo
compra_cliente.set_table_styles([tabla,indice])

In [39]:
#vamos aplicar el metodo st_table_styles sobre nuestro objeto estilo
compra_cliente.set_table_styles({
    'Total':[
        {
            'selector':'th',
            'props':'border-top: 2px solid #181818'
        },
        {
            'selector':'td',
            'props':'border-top: 2px solid #181818'
        }
    ],
    'B2B':[
        {
            'selector':'th',
            'props':'border-top: 2px solid #181818'
        },
        {
            'selector':'td',
            'props':'border-top: 2px solid #181818'
        }
    ]
}, overwrite=False, axis=1)

In [77]:
#visualizar la tabla que creamos en el codigo que sigue
colores_columna = pd.DataFrame(['false','true','false'], index=df_cliente['Total'].index, columns=['Total'])
colores_columna

                  Total
segmento_cliente
B2B               false
B2C                true
Total             false

In [78]:
#crea un selector personalizado
compra_cliente.set_table_styles({
    'Total':[{
      #donde sea verdadero lo haga
        'selector':'.true',
        'props':'background-color: #D8D8D8'
    }]
},overwrite=False,axis=0)

#construir un data frame que va hacer nuestra mascara ([valores que va tener flaso,verdadero,falso para que tenga las mimas dimensiones],indice va el df del cliente,columna va ser total)
colores_columna = pd.DataFrame(['false','true','false'], index=df_cliente['Total'].index, columns=['Total'])

#otro metodo que podemos utilizar
compra_cliente.set_td_classes(colores_columna)